import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

// Entity representing a Todo item in the database
@Entity()
export class Todo {
  // Auto-incremented primary key (internal DB id)
  @PrimaryGeneratedColumn()
  id!: number;

  // Public UUID for the todo, unique identifier generated by the DB
  @Column({ type: "uuid", unique: true, default: () => "gen_random_uuid()" })
  uuid!: string;

  // The actual content/text of the todo item
  @Column()
  content!: string;

  // UUID of the user who owns this todo (foreign key reference)
  @Column({ type: "uuid" })
  user_uuid!: string;
}
