name: E2E Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # required for Vite build

      # 3. Install dependencies (root + e2e)
      - run: yarn install --frozen-lockfile
      - run: cd e2e && yarn install --frozen-lockfile

      # 4. Start services with docker-compose
      - name: Start services
        run: docker compose up -d --build
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          USER_DB_NAME: ${{ secrets.USER_DB_NAME }}
          USER_DB_PORT: ${{ secrets.USER_DB_PORT }}
          TODO_DB_NAME: ${{ secrets.TODO_DB_NAME }}
          TODO_DB_PORT: ${{ secrets.TODO_DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - run: docker ps -a

      # 5. Install Playwright browsers
      - run: cd e2e && npx playwright install --with-deps

      # 6. Wait for services
      - name: Wait for API & Client
        run: |
          npx wait-on http://localhost:3000 http://localhost:5000 http://localhost:5001

      # 7. Run tests
      - run: cd e2e && yarn test --reporter=dot
