name: E2E Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Node.js (20+ needed for Vite)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      # 3. Install dependencies (root + e2e)
      - run: yarn install --frozen-lockfile
      - run: cd e2e && yarn install --frozen-lockfile

      # 4. Start services with docker-compose
      - name: Start services
        run: docker compose up -d --build
        env:
          DB_USER: ${{ secrets.DB_USER || 'postgres' }}
          DB_PASS: ${{ secrets.DB_PASS || 'postgres' }}
          USER_DB_NAME: ${{ secrets.USER_DB_NAME || 'userdb' }}
          USER_DB_PORT: ${{ secrets.USER_DB_PORT || '5432' }}
          TODO_DB_NAME: ${{ secrets.TODO_DB_NAME || 'tododb' }}
          TODO_DB_PORT: ${{ secrets.TODO_DB_PORT || '5432' }}
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'supersecret' }}

      # 5. Debug services status
      - run: docker compose ps
      - run: docker compose logs --tail=100

      # 6. Install Playwright browsers
      - run: cd e2e && npx playwright install --with-deps

      # 7. Wait for services (fail fast if not ready)
      - name: Wait for API & Client
        run: |
          npx wait-on --timeout 60000 --interval 2000 \
            http://localhost:3000 \
            http://localhost:5000 \
            http://localhost:5001

      # 8. Run tests
      - run: cd e2e && yarn test --reporter=dot
