name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for PR analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          cd user-service && yarn install --frozen-lockfile && cd ..
          cd todo-service && yarn install --frozen-lockfile && cd ..
          cd client && yarn install --frozen-lockfile && cd ..

      - name: Run service tests
        run: |
          cd user-service && yarn test --coverage && cd ..
          cd todo-service && yarn test --coverage && cd ..

      - name: Run client tests
        run: |
          cd client && yarn test:coverage && cd ..

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
